#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

staged=$(git diff --cached --name-only | grep -E '\.(js|jsx|ts|tsx)$')

echo "preparing"
# if staged is not empty
if [ -n "$staged" ]
then
  echo "linting"
  yarn prettier --ignore-unknown --no-error-on-unmatched-pattern -c ${staged}
  yarn eslint --no-error-on-unmatched-pattern --max-warnings 0 "${staged}"
  yarn test run
fi